name: lint-commits

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  commitlint:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install commitlint
        run: |
          npm install --save-dev @commitlint/cli @commitlint/config-conventional

      - name: Run commitlint on PR commits
        id: run-lint
        run: |
          if npx commitlint \
                --from="${{ github.event.pull_request.base.sha }}" \
                --to="${{ github.event.pull_request.head.sha }}" \
                --verbose \
                > lint-report.txt 2>&1; then
            echo "lint_ok=true" >> $GITHUB_OUTPUT
          else
            echo "lint_ok=false" >> $GITHUB_OUTPUT

            echo "lint_report<<EOF" >> $GITHUB_OUTPUT
            cat lint-report.txt >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi
        continue-on-error: true

      - name: Find existing commitlint comment
        id: find-comment
        uses: peter-evans/find-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: "<!-- commitlint-comment -->"

      - name: Update existing comment (if found)
        if: steps.find-comment.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          edit-mode: replace
          body: |
            <!-- commitlint-comment -->
            **Commit Message Format Errors Detected**  
            Please follow the [Conventional Commits](https://www.conventionalcommits.org/) specification.  
            ---
            ```text
            ${{ steps.run-lint.outputs.lint_report }}
            ```

      - name: Create new commitlint comment (if none exists)
        if: steps.find-comment.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            <!-- commitlint-comment -->
            **Commit Message Format Errors Detected**  
            Please follow the [Conventional Commits](https://www.conventionalcommits.org/) specification.  
            ---
            ```text
            ${{ steps.run-lint.outputs.lint_report }}
            ```
        continue-on-error: true
